[package]
name = "fishrambeta-plot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(target_os = "macos")']
metal="0.26.0"
[target.'cfg(not(target_os = "macos"))']
ash = "0.37.3"